version: "3.8"
services:
  apache:
    hostname: apache
    image: ${CIC_APACHE_IMAGE:-cic-apache:latest}
    ports:
      - "21000:80"
    volumes:
      - type: bind
        source: ./running-servers/apache
        target: /usr/local/apache2/logs
    networks:
      - cic-net
  wladmin:
    hostname: wladmin
    image: ${CIC_APP_IMAGE:-cic-domain:latest}
    ports:
      - "21001:7001"
    volumes:
      - type: bind
        source: ./running-servers
        target: /apps/oracle/cicdomain/servers
    networks:
      - cic-net
    env_file: ./cic.properties
    entrypoint: container-scripts/startAdmin.sh
  wlserver1:
    hostname: wlserver1
    image: ${CIC_APP_IMAGE:-cic-domain:latest}
    ports:
      - "21011:7001"
    volumes:
      - type: bind
        source: ./running-servers
        target: /apps/oracle/cicdomain/servers
    networks:
      - cic-net
    env_file: ./cic.properties
    entrypoint: container-scripts/startNodeManagerAndManagedServer.sh
  wlserver2:
    hostname: wlserver2
    image: ${CIC_APP_IMAGE:-cic-domain:latest}
    ports:
      - "21012:7001"
    volumes:
      - type: bind
        source: ./running-servers
        target: /apps/oracle/cicdomain/servers
    networks:
      - cic-net
    env_file: ./cic.properties
    entrypoint: container-scripts/startNodeManagerAndManagedServer.sh
networks:
  cic-net: 
